/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Random;

public class Monster {
    String name;
    int rare;// 1:normal,2:uncommon,3:rare,4:ultra rare
    int hp;
    int attack;
  
    Monster() {
      Random random = new Random();
      this.name = this.summonMonster(random.nextInt(5));
      this.rare = random.nextInt(5);
      this.hp = 100;
      this.attack=10;
    }

    Monster(int number,int rare) {
      this.name = this.summonMonster(number);
      this.rare = rare;
      this.hp = 100;
      this.attack=10;
    }
  
    String summonMonster(int mnumber) {
      String monsters[] = { "スライム", "サハギン", "ドラゴン", "デュラハン", "シーサーペント" };
      return monsters[mnumber];
    }
  
    @Override
    public String toString() {
      return this.name + ":レア度[" + this.rare + "],HP[" + this.hp + "],攻撃力[" + this.attack + "]";
    }
  }
