/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
    @Test public void testMonster() {
        Monster classUnderTest = new Monster();
        classUnderTest.name="OIT";
        classUnderTest.rare=3;
        assertEquals("OIT:レア度[3],HP[100],攻撃力[10]", classUnderTest.toString());
    }
}
