/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class PlayerTest {
    @Test public void testplayer() {
        Player classUnderTest = new Player("yamada", 50);

        int[] monsterIds = {0, 1, 2, 3, 4};
        int[] rareIds = {1, 2, 3, 4, 5};
        classUnderTest.drawMonsters(monsterIds, rareIds);

        String expectedContent = "hp: 50\n" +
        "Deck: yamada\n" +
        "スライム:レア度[1],HP[100]\n" +
        "サハギン:レア度[2],HP[100]\n" +
        "ドラゴン:レア度[3],HP[100]\n" +
        "デュラハン:レア度[4],HP[100]\n" +
        "シーサーペント:レア度[5],HP[100]\n";


        assertEquals(expectedContent, classUnderTest.toString());
    }
}
