/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class SeMonsterGameTest {
    @Test public void testSeMonsterGame() {
        SeMonsterGame classUnderTest = new SeMonsterGame();
        classUnderTest.addPlayer("OIT");
        assertEquals(true, classUnderTest.isExist("OIT"));
    }
}
